---
title: "Import Apple Health Data"
description: >
  Account lists
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Import Apple Health Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Parsing

Initial Parsing of Health Data File (Takes some time). This needs to be done only once per data pull. The parsed data can then be saved as in the .rds format

```{r}
library(health2R)
library(tidyverse)
```


```{r,eval = F}

parsed_data <- 
  parse_healthdata(filename = "../dev/data/mp_export.zip",
                   type = "apple")

saveRDS(parsed_data,"../dev/data/parsed_healthdata_mp.rds")
```

## Exploring

Note: remove "../" when in VS code, use ../ when in RStudio

```{r}
parsed_data <- 
  readRDS("../dev/data/parsed_healthdata_mp.rds")
```

```{r}
parsed_data %>% 
  head(25)
```

Print 10 most frequent types

```{r}
parsed_data$type %>% table() %>% sort(decreasing = TRUE) %>% head(10)
```

```{r}
# df filter where type == "HKQuantityTypeIdentifierHeartRate"
heart <- parsed_data %>% filter(type == "HKQuantityTypeIdentifierHeartRate")
heart$value <- as.numeric(heart$value)
```


```{r}
library(ggplot2)

ggplot(heart, 
    aes(x = startDate, y = value)) + geom_point() +
    # zoom in only 20th of march 2022
    scale_x_datetime(limits = c(as.POSIXct("2022-03-29 00:00:00"), as.POSIXct("2022-03-29 23:59:59")))
```

